/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Areas: typeof import('./components/Areas.vue')['default']
    Funcionarios: typeof import('./components/Funcionarios.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Perfis: typeof import('./components/Perfis.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
