/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Areas: typeof import('./components/Areas.vue')['default']
    Avaliacao: typeof import('./components/Avaliacao.vue')['default']
    CadastroPerguntas: typeof import('./components/CadastroPerguntas.vue')['default']
    Competencia: typeof import('./components/Competencia.vue')['default']
    copia: typeof import('./components/Lista - copia.vue')['default']
    Copia: typeof import('./components/perfilBase - Copia.vue')['default']
    ExperienciaModal: typeof import('./components/ExperienciaModal.vue')['default']
    Funcionarios: typeof import('./components/Funcionarios.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Inicio: typeof import('./components/Inicio.vue')['default']
    Lista: typeof import('./components/Lista.vue')['default']
    PerfilBase: typeof import('./components/perfilBase.vue')['default']
    PerfilFun: typeof import('./components/perfilFun.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teste: typeof import('./components/Teste.vue')['default']
  }
}
