--
-- PostgreSQL database dump
--

\restrict DC6R4r7mdQ3dV7mR8wfg2XHHqN4i6ErXctmGVT4G9XpiTlxTTOVtAFV0DRQASKN

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-11-11 16:42:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 18692)
-- Name: tb_cad_area; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_area (
    codigo integer NOT NULL,
    nome character varying(255) NOT NULL,
    descricao character varying(255)
);


ALTER TABLE public.tb_cad_area OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 18697)
-- Name: tb_cad_area_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cad_area_codigo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cad_area_codigo_seq OWNER TO postgres;

--
-- TOC entry 5008 (class 0 OID 0)
-- Dependencies: 218
-- Name: tb_cad_area_codigo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tb_cad_area_codigo_seq OWNED BY public.tb_cad_area.codigo;


--
-- TOC entry 219 (class 1259 OID 18698)
-- Name: tb_cad_avaliacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_avaliacao (
    codigo integer NOT NULL,
    titulo character varying(255) NOT NULL,
    status character varying(50),
    data_criacao date DEFAULT CURRENT_TIMESTAMP,
    data_prazo date,
    codigo_criador integer
);


ALTER TABLE public.tb_cad_avaliacao OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 18702)
-- Name: tb_cad_avaliacao_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cad_avaliacao_codigo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cad_avaliacao_codigo_seq OWNER TO postgres;

--
-- TOC entry 5009 (class 0 OID 0)
-- Dependencies: 220
-- Name: tb_cad_avaliacao_codigo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tb_cad_avaliacao_codigo_seq OWNED BY public.tb_cad_avaliacao.codigo;


--
-- TOC entry 221 (class 1259 OID 18703)
-- Name: tb_cad_avaliacao_pergunta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_avaliacao_pergunta (
    codigo_pergunta bigint NOT NULL,
    codigo_avaliacao integer NOT NULL,
    codigo bigint NOT NULL
);


ALTER TABLE public.tb_cad_avaliacao_pergunta OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 18961)
-- Name: tb_cad_avaliacao_pergunta_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_cad_avaliacao_pergunta ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_cad_avaliacao_pergunta_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 18706)
-- Name: tb_cad_competencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_competencia (
    codigo integer NOT NULL,
    nome character varying(255) NOT NULL
);


ALTER TABLE public.tb_cad_competencia OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 18709)
-- Name: tb_cad_competencia_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cad_competencia_codigo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cad_competencia_codigo_seq OWNER TO postgres;

--
-- TOC entry 5010 (class 0 OID 0)
-- Dependencies: 223
-- Name: tb_cad_competencia_codigo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tb_cad_competencia_codigo_seq OWNED BY public.tb_cad_competencia.codigo;


--
-- TOC entry 224 (class 1259 OID 18710)
-- Name: tb_cad_funcionario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_funcionario (
    codigo integer NOT NULL,
    nome_completo character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    senha_hash character varying(255) NOT NULL,
    telefone character varying(255),
    cpf character varying(255),
    codigo_perfil integer NOT NULL,
    codigo_area integer,
    data_cadastro timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    resumo character varying(255),
    titulo_profissional character varying(255),
    localizacao character varying(255),
    codigo_gestor integer
);


ALTER TABLE public.tb_cad_funcionario OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 18716)
-- Name: tb_cad_funcionario_avaliacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_funcionario_avaliacao (
    codigo bigint NOT NULL,
    codigo_funcionario_avalidado integer,
    codigo_avaliacao integer,
    comentario_colaborador text,
    comentario_supervisao text,
    resultado_status character varying(30),
    nota integer,
    CONSTRAINT tb_cad_funcionario_avalicacao_resultado_status_check CHECK (((resultado_status)::text = ANY (ARRAY[('BOM'::character varying)::text, ('INSUFICIENTE'::character varying)::text, ('APROVADO'::character varying)::text, ('REPROVADO'::character varying)::text, ('PENDENTE'::character varying)::text])))
);


ALTER TABLE public.tb_cad_funcionario_avaliacao OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 18900)
-- Name: tb_cad_funcionario_avalicacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_funcionario_avalicacao (
    codigo bigint NOT NULL,
    comentario_colaborador text,
    comentario_supervisao text,
    nota integer,
    resultado_status character varying(30),
    codigo_avalicacao integer NOT NULL,
    codigo_funcionario_avalidado integer NOT NULL
);


ALTER TABLE public.tb_cad_funcionario_avalicacao OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 18722)
-- Name: tb_cad_funcionario_avalicacao_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cad_funcionario_avalicacao_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cad_funcionario_avalicacao_codigo_seq OWNER TO postgres;

--
-- TOC entry 5011 (class 0 OID 0)
-- Dependencies: 226
-- Name: tb_cad_funcionario_avalicacao_codigo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tb_cad_funcionario_avalicacao_codigo_seq OWNED BY public.tb_cad_funcionario_avaliacao.codigo;


--
-- TOC entry 227 (class 1259 OID 18723)
-- Name: tb_cad_funcionario_certificado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_funcionario_certificado (
    codigo integer NOT NULL,
    codigo_funcionario integer,
    certificado character varying(255)
);


ALTER TABLE public.tb_cad_funcionario_certificado OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 18987)
-- Name: tb_cad_funcionario_certificado_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_cad_funcionario_certificado ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_cad_funcionario_certificado_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 18726)
-- Name: tb_cad_funcionario_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cad_funcionario_codigo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cad_funcionario_codigo_seq OWNER TO postgres;

--
-- TOC entry 5012 (class 0 OID 0)
-- Dependencies: 228
-- Name: tb_cad_funcionario_codigo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tb_cad_funcionario_codigo_seq OWNED BY public.tb_cad_funcionario.codigo;


--
-- TOC entry 229 (class 1259 OID 18727)
-- Name: tb_cad_funcionario_competencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_funcionario_competencia (
    codigo_funcionario integer NOT NULL,
    codigo_competencia integer NOT NULL,
    nota integer,
    inserido_por character varying(20),
    CONSTRAINT tb_cad_funcionario_competencia_inserido_por_check CHECK (((inserido_por)::text = ANY (ARRAY[('USUARIO'::character varying)::text, ('GESTOR'::character varying)::text])))
);


ALTER TABLE public.tb_cad_funcionario_competencia OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 18731)
-- Name: tb_cad_funcionario_historico_experiencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_funcionario_historico_experiencia (
    codigo integer NOT NULL,
    cargo character varying(255) NOT NULL,
    empresa character varying(255) NOT NULL,
    data_inicio date NOT NULL,
    data_fim date,
    descricao character varying(255),
    codigo_funcionario integer NOT NULL
);


ALTER TABLE public.tb_cad_funcionario_historico_experiencia OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 18736)
-- Name: tb_cad_funcionario_perfil_experiencia_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cad_funcionario_perfil_experiencia_codigo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cad_funcionario_perfil_experiencia_codigo_seq OWNER TO postgres;

--
-- TOC entry 5013 (class 0 OID 0)
-- Dependencies: 231
-- Name: tb_cad_funcionario_perfil_experiencia_codigo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tb_cad_funcionario_perfil_experiencia_codigo_seq OWNED BY public.tb_cad_funcionario_historico_experiencia.codigo;


--
-- TOC entry 232 (class 1259 OID 18737)
-- Name: tb_cad_perfil; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_perfil (
    codigo integer NOT NULL,
    nome character varying(255) NOT NULL,
    descricao character varying(255)
);


ALTER TABLE public.tb_cad_perfil OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 18742)
-- Name: tb_cad_perfil_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cad_perfil_codigo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cad_perfil_codigo_seq OWNER TO postgres;

--
-- TOC entry 5014 (class 0 OID 0)
-- Dependencies: 233
-- Name: tb_cad_perfil_codigo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tb_cad_perfil_codigo_seq OWNED BY public.tb_cad_perfil.codigo;


--
-- TOC entry 234 (class 1259 OID 18743)
-- Name: tb_cad_pergunta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_pergunta (
    codigo bigint NOT NULL,
    pergunta character varying(255),
    codigo_competencia bigint,
    tipo_pergunta character varying(255)
);


ALTER TABLE public.tb_cad_pergunta OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 18746)
-- Name: tb_cad_pergunta_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cad_pergunta_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cad_pergunta_codigo_seq OWNER TO postgres;

--
-- TOC entry 5015 (class 0 OID 0)
-- Dependencies: 235
-- Name: tb_cad_pergunta_codigo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tb_cad_pergunta_codigo_seq OWNED BY public.tb_cad_pergunta.codigo;


--
-- TOC entry 236 (class 1259 OID 18747)
-- Name: tb_cad_pergunta_opcao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_pergunta_opcao (
    codigo bigint NOT NULL,
    codigo_pergunta bigint NOT NULL,
    descricao_opcao text NOT NULL,
    is_correta boolean DEFAULT false NOT NULL
);


ALTER TABLE public.tb_cad_pergunta_opcao OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 18753)
-- Name: tb_cad_pergunta_opcao_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cad_pergunta_opcao_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cad_pergunta_opcao_codigo_seq OWNER TO postgres;

--
-- TOC entry 5016 (class 0 OID 0)
-- Dependencies: 237
-- Name: tb_cad_pergunta_opcao_codigo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tb_cad_pergunta_opcao_codigo_seq OWNED BY public.tb_cad_pergunta_opcao.codigo;


--
-- TOC entry 238 (class 1259 OID 18754)
-- Name: tb_cad_resposta_colaborador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cad_resposta_colaborador (
    codigo bigint NOT NULL,
    codigo_funcionario_avaliacao bigint NOT NULL,
    codigo_pergunta bigint NOT NULL,
    resposta_texto text,
    codigo_pergunta_opcao_selecionada bigint
);


ALTER TABLE public.tb_cad_resposta_colaborador OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 18759)
-- Name: tb_cad_resposta_colaborador_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cad_resposta_colaborador_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cad_resposta_colaborador_codigo_seq OWNER TO postgres;

--
-- TOC entry 5017 (class 0 OID 0)
-- Dependencies: 239
-- Name: tb_cad_resposta_colaborador_codigo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tb_cad_resposta_colaborador_codigo_seq OWNED BY public.tb_cad_resposta_colaborador.codigo;


--
-- TOC entry 4758 (class 2604 OID 18760)
-- Name: tb_cad_area codigo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cad_area ALTER COLUMN codigo SET DEFAULT nextval('public.tb_cad_area_codigo_seq'::regclass);


--
-- TOC entry 4759 (class 2604 OID 18761)
-- Name: tb_cad_avaliacao codigo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cad_avaliacao ALTER COLUMN codigo SET DEFAULT nextval('public.tb_cad_avaliacao_codigo_seq'::regclass);


--
-- TOC entry 4761 (class 2604 OID 18762)
-- Name: tb_cad_competencia codigo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cad_competencia ALTER COLUMN codigo SET DEFAULT nextval('public.tb_cad_competencia_codigo_seq'::regclass);


--
-- TOC entry 4762 (class 2604 OID 18763)
-- Name: tb_cad_funcionario codigo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cad_funcionario ALTER COLUMN codigo SET DEFAULT nextval('public.tb_cad_funcionario_codigo_seq'::regclass);


--
-- TOC entry 4764 (class 2604 OID 18764)
-- Name: tb_cad_funcionario_avaliacao codigo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cad_funcionario_avaliacao ALTER COLUMN codigo SET DEFAULT nextval('public.tb_cad_funcionario_avalicacao_codigo_seq'::regclass);


--
-- TOC entry 4765 (class 2604 OID 18765)
-- Name: tb_cad_funcionario_historico_experiencia codigo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cad_funcionario_historico_experiencia ALTER COLUMN codigo SET DEFAULT nextval('public.tb_cad_funcionario_perfil_experiencia_codigo_seq'::regclass);


--
-- TOC entry 4766 (class 2604 OID 18766)
-- Name: tb_cad_perfil codigo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cad_perfil ALTER COLUMN codigo SET DEFAULT nextval('public.tb_cad_perfil_codigo_seq'::regclass);


--
-- TOC entry 4767 (class 2604 OID 18767)
-- Name: tb_cad_pergunta codigo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cad_pergunta ALTER COLUMN codigo SET DEFAULT nextval('public.tb_cad_pergunta_codigo_seq'::regclass);


--
-- TOC entry 4768 (class 2604 OID 18768)
-- Name: tb_cad_pergunta_opcao codigo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cad_pergunta_opcao ALTER COLUMN codigo SET DEFAULT nextval('public.tb_cad_pergunta_opcao_codigo_seq'::regclass);


--
-- TOC entry 4770 (class 2604 OID 18769)
-- Name: tb_cad_resposta_colaborador codigo; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cad_resposta_colaborador ALTER COLUMN codigo SET DEFAULT nextval('public.tb_cad_resposta_colaborador_codigo_seq'::regclass);


--
-- TOC entry 4977 (class 0 OID 18692)
-- Dependencies: 217
-- Data for Name: tb_cad_area; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_area (codigo, nome, descricao) FROM stdin;
1	Tecnologia	Desenvolvimento e infraestrutura.
2	Recursos Humanos	Gestão de pessoas.
3	Financeiro	Gestão financeira e contábil.
4	Marketing	Estratégia de marca e comunicação.
5	Operações	Operações e logística.
\.


--
-- TOC entry 4979 (class 0 OID 18698)
-- Dependencies: 219
-- Data for Name: tb_cad_avaliacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_avaliacao (codigo, titulo, status, data_criacao, data_prazo, codigo_criador) FROM stdin;
20	teste	Rascunho	2025-10-29	\N	\N
21	Avaliação Trimestral - TI	Rascunho	2025-11-10	\N	\N
\.


--
-- TOC entry 4981 (class 0 OID 18703)
-- Dependencies: 221
-- Data for Name: tb_cad_avaliacao_pergunta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_avaliacao_pergunta (codigo_pergunta, codigo_avaliacao, codigo) FROM stdin;
48	21	68
47	20	67
\.


--
-- TOC entry 4982 (class 0 OID 18706)
-- Dependencies: 222
-- Data for Name: tb_cad_competencia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_competencia (codigo, nome) FROM stdin;
1	Java
2	PostgreSQL
3	Excel Avançado
4	Inglês Fluente
5	Python
6	Gestão de Projetos
7	Power BI
8	Liderança
9	Comunicação
10	Metodologia Scrum
11	Kanban
12	Trabalho em Equipe
13	Resolução de Conflitos
14	Inteligência Emocional
15	Negociação
16	Oratória e Apresentação
17	Pensamento Crítico
18	Gestão do Tempo
19	Adaptabilidade
20	Criatividade e Inovação
21	Análise de Dados
22	Business Intelligence (BI)
23	SQL
24	React
25	Angular
26	Node.js
27	Arquitetura de Microsserviços
28	Cloud Computing
29	Amazon Web Services (AWS)
30	Microsoft Azure
31	Google Cloud Platform (GCP)
32	Docker
33	Kubernetes
34	CI/CD (Integração e Entrega Contínua)
35	Testes Automatizados
36	Segurança da Informação
37	UX Design (User Experience)
38	UI Design (User Interface)
39	Design Thinking
40	Planejamento Estratégico
41	Gestão de Pessoas
42	Finanças Corporativas
43	Marketing Digital
44	SEO (Search Engine Optimization)
45	Gestão de Produtos
46	Atendimento ao Cliente
47	Prototipação
48	Git (Controle de Versão)
49	C# / .NET
50	NoSQL
51	PHP
52	DevOps
53	Inteligência Artificial
54	Machine Learning
55	Big Data
56	Marketing de Conteúdo
57	Linguagem R
58	Go (Golang)
59	Vue.js
60	Gestão de Orçamento
\.


--
-- TOC entry 4984 (class 0 OID 18710)
-- Dependencies: 224
-- Data for Name: tb_cad_funcionario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_funcionario (codigo, nome_completo, email, senha_hash, telefone, cpf, codigo_perfil, codigo_area, data_cadastro, resumo, titulo_profissional, localizacao, codigo_gestor) FROM stdin;
10	Vanessa Lima	vanessa.lima@example.com	$2b$12$...	(11) 92222-0010	222.000.000-10	2	2	2025-09-19 19:28:18.798086-03	\N	Supervisora de Recrutamento	São José dos Campos, SP	2
2	Beatriz Campos	beatriz.campos@example.com	$2b$12$...	(11) 91111-0002	111.000.000-02	1	2	2025-09-19 19:28:18.798086-03	\N	Diretora de Recursos Humanos	São José dos Campos, SP	\N
3	Ricardo Almeida	ricardo.almeida@example.com	$2b$12$...	(11) 91111-0003	111.000.000-03	1	3	2025-09-19 19:28:18.798086-03	\N	Diretor Financeiro	São José dos Campos, SP	\N
4	Sofia Ribeiro	sofia.ribeiro@example.com	$2b$12$...	(11) 91111-0004	111.000.000-04	1	4	2025-09-19 19:28:18.798086-03	\N	Diretora de Marketing	São José dos Campos, SP	\N
5	Mateus Rocha	mateus.rocha@example.com	$2b$12$...	(11) 91111-0005	111.000.000-05	1	5	2025-09-19 19:28:18.798086-03	\N	Diretor de Operações	São José dos Campos, SP	\N
6	Laura Mendes	laura.mendes@example.com	$2b$12$...	(11) 91111-0006	111.000.000-06	1	1	2025-09-19 19:28:18.798086-03	\N	Diretora de Inovação	São José dos Campos, SP	\N
7	Gabriel Costa	gabriel.costa@example.com	$2b$12$...	(11) 91111-0007	111.000.000-07	1	2	2025-09-19 19:28:18.798086-03	\N	Diretor de Talentos	São José dos Campos, SP	\N
11	Rodrigo Nogueira	rodrigo.nogueira@example.com	$2b$12$...	(11) 92222-0011	222.000.000-11	2	2	2025-09-19 19:28:18.798086-03	\N	Supervisor de Departamento Pessoal	São José dos Campos, SP	\N
12	Amanda Azevedo	amanda.azevedo@example.com	$2b$12$...	(11) 92222-0012	222.000.000-12	2	3	2025-09-19 19:28:18.798086-03	\N	Supervisora Contábil	São José dos Campos, SP	\N
13	Lucas Martins	lucas.martins@example.com	$2b$12$...	(11) 92222-0013	222.000.000-13	2	3	2025-09-19 19:28:18.798086-03	\N	Supervisor Financeiro	São José dos Campos, SP	\N
14	Carolina Dias	carolina.dias@example.com	$2b$12$...	(11) 92222-0014	222.000.000-14	2	4	2025-09-19 19:28:18.798086-03	\N	Supervisora de Mídia Digital	São José dos Campos, SP	\N
15	Thiago Gonçalves	thiago.goncalves@example.com	$2b$12$...	(11) 92222-0015	222.000.000-15	2	4	2025-09-19 19:28:18.798086-03	\N	Supervisor de Criação	São José dos Campos, SP	\N
16	Isabela Freitas	isabela.freitas@example.com	$2b$12$...	(11) 92222-0016	222.000.000-16	2	5	2025-09-19 19:28:18.798086-03	\N	Supervisora de Logística	São José dos Campos, SP	\N
17	Vinicius Andrade	vinicius.andrade@example.com	$2b$12$...	(11) 92222-0017	222.000.000-17	2	5	2025-09-19 19:28:18.798086-03	\N	Supervisor de Produção	São José dos Campos, SP	\N
20	Manuela Barbosa	manuela.barbosa@example.com	$2b$12$...	(11) 92222-0020	222.000.000-20	2	2	2025-09-19 19:28:18.798086-03	\N	Supervisora de Aquisição de Talentos	São José dos Campos, SP	\N
21	Davi Castro	davi.castro@example.com	$2b$12$...	(11) 92222-0021	222.000.000-21	2	2	2025-09-19 19:28:18.798086-03	\N	Supervisor de Remuneração e Benefícios	São José dos Campos, SP	\N
28	Valentina Carvalho	valentina.carvalho@example.com	$2b$12$...	(11) 93333-0028	333.000.000-28	2	2	2025-09-19 19:28:18.798086-03	\N	Analista de Recrutamento e Seleção	São José dos Campos, SP	\N
29	Arthur Ferreira	arthur.ferreira@example.com	$2b$12$...	(11) 93333-0029	333.000.000-29	2	2	2025-09-19 19:28:18.798086-03	\N	Assistente de RH	São José dos Campos, SP	\N
30	Lívia Rodrigues	livia.rodrigues@example.com	$2b$12$...	(11) 93333-0030	333.000.000-30	2	2	2025-09-19 19:28:18.798086-03	\N	Especialista em Treinamento	São José dos Campos, SP	\N
31	Pedro Gomes	pedro.gomes@example.com	$2b$12$...	(11) 93333-0031	333.000.000-31	2	2	2025-09-19 19:28:18.798086-03	\N	Analista de Departamento Pessoal	São José dos Campos, SP	\N
32	Yasmin Almeida	yasmin.almeida@example.com	$2b$12$...	(11) 93333-0032	333.000.000-32	2	2	2025-09-19 19:28:18.798086-03	\N	Assistente de Benefícios	São José dos Campos, SP	\N
33	Enzo Barros	enzo.barros@example.com	$2b$12$...	(11) 93333-0033	333.000.000-33	2	2	2025-09-19 19:28:18.798086-03	\N	Generalista de RH	São José dos Campos, SP	\N
34	Mariana Costa	mariana.costa@example.com	$2b$12$...	(11) 93333-0034	333.000.000-34	2	3	2025-09-19 19:28:18.798086-03	\N	Analista Contábil	São José dos Campos, SP	\N
35	Rafael Martins	rafael.martins@example.com	$2b$12$...	(11) 93333-0035	333.000.000-35	2	3	2025-09-19 19:28:18.798086-03	\N	Assistente Financeiro	São José dos Campos, SP	\N
36	Isis Castro	isis.castro@example.com	$2b$12$...	(11) 93333-0036	333.000.000-36	2	3	2025-09-19 19:28:18.798086-03	\N	Controller Jr	São José dos Campos, SP	\N
37	Cauã Dias	caua.dias@example.com	$2b$12$...	(11) 93333-0037	333.000.000-37	2	3	2025-09-19 19:28:18.798086-03	\N	Analista de Tesouraria	São José dos Campos, SP	\N
38	Emanuelly Pires	emanuelly.pires@example.com	$2b$12$...	(11) 93333-0038	333.000.000-38	2	4	2025-09-19 19:28:18.798086-03	\N	Analista de Mídia Paga	São José dos Campos, SP	\N
39	Noah Ribeiro	noah.ribeiro@example.com	$2b$12$...	(11) 93333-0039	333.000.000-39	2	4	2025-09-19 19:28:18.798086-03	\N	Designer Gráfico	São José dos Campos, SP	\N
40	Catarina Santos	catarina.santos@example.com	$2b$12$...	(11) 93333-0040	333.000.000-40	2	4	2025-09-19 19:28:18.798086-03	\N	Social Media	São José dos Campos, SP	\N
41	Anthony Cunha	anthony.cunha@example.com	$2b$12$...	(11) 93333-0041	333.000.000-41	2	4	2025-09-19 19:28:18.798086-03	\N	Analista de SEO	São José dos Campos, SP	\N
8	Juliana Paiva	juliana.paiva@example.com	$2b$12$...	(11) 92222-0008	222.000.000-08	2	1	2025-09-19 19:28:18.798086-03	\N	Supervisora de Desenvolvimento	São José dos Campos, SP	1
9	Felipe Barros	felipe.barros@example.com	$2b$12$...	(11) 92222-0009	222.000.000-09	2	1	2025-09-19 19:28:18.798086-03	\N	Supervisor de Infraestrutura	São José dos Campos, SP	1
1	Leonardo Vianna	leonardo.vianna@example.com	$2b$12$...	(11) 91111-0001	111.000.000-01	1	1	2025-09-19 19:28:18.798086-03	aaaa	Diretor de Tecnologia	São José dos Campos, SP	\N
42	Liz Oliveira	liz.oliveira@example.com	$2b$12$...	(11) 93333-0042	333.000.000-42	2	5	2025-09-19 19:28:18.798086-03	\N	Analista de Logística	São José dos Campos, SP	\N
43	Benjamin Sousa	benjamin.sousa@example.com	$2b$12$...	(11) 93333-0043	333.000.000-43	2	5	2025-09-19 19:28:18.798086-03	\N	Assistente de Operações	São José dos Campos, SP	\N
44	Eloah Silva	eloah.silva@example.com	$2b$12$...	(11) 93333-0044	333.000.000-44	2	5	2025-09-19 19:28:18.798086-03	\N	Líder de Turno	São José dos Campos, SP	\N
45	Lucca Pereira	lucca.pereira@example.com	$2b$12$...	(11) 93333-0045	333.000.000-45	2	5	2025-09-19 19:28:18.798086-03	\N	Planejador de Produção	São José dos Campos, SP	\N
50	Helena Gomes	helena.gomes@example.com	$2b$12$...	(11) 93333-0050	333.000.000-50	2	2	2025-09-19 19:28:18.798086-03	\N	Tech Recruiter	São José dos Campos, SP	\N
51	Miguel Almeida	miguel.almeida@example.com	$2b$12$...	(11) 93333-0051	333.000.000-51	2	2	2025-09-19 19:28:18.798086-03	\N	Analista de Cargos e Salários	São José dos Campos, SP	\N
52	Cecília Barros	cecilia.barros@example.com	$2b$12$...	(11) 93333-0052	333.000.000-52	2	2	2025-09-19 19:28:18.798086-03	\N	Analista de Sistemas	São José dos Campos, SP	\N
53	Ravi Costa	ravi.costa@example.com	$2b$12$...	(11) 93333-0053	333.000.000-53	2	2	2025-09-19 19:28:18.798086-03	\N	Analista de Negócios	São José dos Campos, SP	\N
58	Sophia Ribeiro	sophia.ribeiro@example.com	$2b$12$...	(11) 93333-0058	333.000.000-58	2	2	2025-09-19 19:28:18.798086-03	\N	Recrutador	São José dos Campos, SP	\N
59	João Miguel Santos	joaomiguel.santos@example.com	$2b$12$...	(11) 93333-0059	333.000.000-59	2	2	2025-09-19 19:28:18.798086-03	\N	Assistente Administrativo	São José dos Campos, SP	\N
60	Lara Cunha	lara.cunha@example.com	$2b$12$...	(11) 93333-0060	333.000.000-60	2	2	2025-09-19 19:28:18.798086-03	\N	Especialista em RH	São José dos Campos, SP	\N
61	Bryan Oliveira	bryan.oliveira@example.com	$2b$12$...	(11) 93333-0061	333.000.000-61	2	2	2025-09-19 19:28:18.798086-03	\N	Analista de Folha de Pagamento	São José dos Campos, SP	\N
62	Esther Sousa	esther.sousa@example.com	$2b$12$...	(11) 93333-0062	333.000.000-62	2	3	2025-09-19 19:28:18.798086-03	\N	Analista de Contas a Pagar	São José dos Campos, SP	\N
63	Lucas Gabriel Silva	lucasgabriel.silva@example.com	$2b$12$...	(11) 93333-0063	333.000.000-63	2	3	2025-09-19 19:28:18.798086-03	\N	Assistente de Contabilidade	São José dos Campos, SP	\N
64	Lavínia Pereira	lavinia.pereira@example.com	$2b$12$...	(11) 93333-0064	333.000.000-64	2	3	2025-09-19 19:28:18.798086-03	\N	Analista de Contas a Receber	São José dos Campos, SP	\N
65	Guilherme Lima	guilherme.lima@example.com	$2b$12$...	(11) 93333-0065	333.000.000-65	2	3	2025-09-19 19:28:18.798086-03	\N	Auditor Interno	São José dos Campos, SP	\N
66	Melissa Carvalho	melissa.carvalho@example.com	$2b$12$...	(11) 93333-0066	333.000.000-66	2	4	2025-09-19 19:28:18.798086-03	\N	Copywriter	São José dos Campos, SP	\N
67	Erick Ferreira	erick.ferreira@example.com	$2b$12$...	(11) 93333-0067	333.000.000-67	2	4	2025-09-19 19:28:18.798086-03	\N	Produtor de Conteúdo	São José dos Campos, SP	\N
68	Elisa Rodrigues	elisa.rodrigues@example.com	$2b$12$...	(11) 93333-0068	333.000.000-68	2	4	2025-09-19 19:28:18.798086-03	\N	Analista de Inbound Marketing	São José dos Campos, SP	\N
69	Enrico Gomes	enrico.gomes@example.com	$2b$12$...	(11) 93333-0069	333.000.000-69	2	4	2025-09-19 19:28:18.798086-03	\N	Designer UX/UI	São José dos Campos, SP	\N
70	Maria Alice Almeida	mariaalice.almeida@example.com	$2b$12$...	(11) 93333-0070	333.000.000-70	2	5	2025-09-19 19:28:18.798086-03	\N	Comprador	São José dos Campos, SP	\N
71	Benjamin Barros	benjamin.barros@example.com	$2b$12$...	(11) 93333-0071	333.000.000-71	2	5	2025-09-19 19:28:18.798086-03	\N	Gerente de Estoque	São José dos Campos, SP	\N
72	Maria Cecília Costa	mariacecilia.costa@example.com	$2b$12$...	(11) 93333-0072	333.000.000-72	2	5	2025-09-19 19:28:18.798086-03	\N	Analista de Qualidade	São José dos Campos, SP	\N
73	Vicente Martins	vicente.martins@example.com	$2b$12$...	(11) 93333-0073	333.000.000-73	2	5	2025-09-19 19:28:18.798086-03	\N	Coordenador de Produção	São José dos Campos, SP	\N
78	Maria Luiza Santos	marialuiza.santos@example.com	$2b$12$...	(11) 93333-0078	333.000.000-78	2	2	2025-09-19 19:28:18.798086-03	\N	Business Partner de RH	São José dos Campos, SP	\N
79	Francisco Cunha	francisco.cunha@example.com	$2b$12$...	(11) 93333-0079	333.000.000-79	2	2	2025-09-19 19:28:18.798086-03	\N	Especialista em Clima Organizacional	São José dos Campos, SP	\N
80	Maria Helena Oliveira	mariahelena.oliveira@example.com	$2b$12$...	(11) 93333-0080	333.000.000-80	2	2	2025-09-19 19:28:18.798086-03	\N	Analista de Benefícios	São José dos Campos, SP	\N
81	Isaac Sousa	isaac.sousa@example.com	$2b$12$...	(11) 93333-0081	333.000.000-81	2	2	2025-09-19 19:28:18.798086-03	\N	Técnico em Segurança do Trabalho	São José dos Campos, SP	\N
86	Gabriela Ferreira	gabriela.ferreira@example.com	$2b$12$...	(11) 93333-0086	333.000.000-86	2	2	2025-09-19 19:28:18.798086-03	\N	Analista de Treinamento e Desenvolvimento	São José dos Campos, SP	\N
87	Ryan Rodrigues	ryan.rodrigues@example.com	$2b$12$...	(11) 93333-0087	333.000.000-87	2	2	2025-09-19 19:28:18.798086-03	\N	Coordenador de RH	São José dos Campos, SP	\N
88	Stella Gomes	stella.gomes@example.com	$2b$12$...	(11) 93333-0088	333.000.000-88	2	2	2025-09-19 19:28:18.798086-03	\N	Analista de Endomarketing	São José dos Campos, SP	\N
89	Daniel Almeida	daniel.almeida@example.com	$2b$12$...	(11) 93333-0089	333.000.000-89	2	2	2025-09-19 19:28:18.798086-03	\N	Assistente de Recrutamento	São José dos Campos, SP	\N
90	Isadora Barros	isadora.barros@example.com	$2b$12$...	(11) 93333-0090	333.000.000-90	2	3	2025-09-19 19:28:18.798086-03	\N	Analista Fiscal	São José dos Campos, SP	\N
91	Calebe Costa	calebe.costa@example.com	$2b$12$...	(11) 93333-0091	333.000.000-91	2	3	2025-09-19 19:28:18.798086-03	\N	Consultor Financeiro	São José dos Campos, SP	\N
92	Ana Laura Martins	analaura.martins@example.com	$2b$12$...	(11) 93333-0092	333.000.000-92	2	3	2025-09-19 19:28:18.798086-03	\N	Analista de Planejamento Financeiro	São José dos Campos, SP	\N
93	Bento Castro	bento.castro@example.com	$2b$12$...	(11) 93333-0093	333.000.000-93	2	3	2025-09-19 19:28:18.798086-03	\N	Controller Sênior	São José dos Campos, SP	\N
94	Allana Dias	allana.dias@example.com	$2b$12$...	(11) 93333-0094	333.000.000-94	2	4	2025-09-19 19:28:18.798086-03	\N	Analista de CRM	São José dos Campos, SP	\N
95	Otávio Pires	otavio.pires@example.com	$2b$12$...	(11) 93333-0095	333.000.000-95	2	4	2025-09-19 19:28:18.798086-03	\N	Especialista em E-commerce	São José dos Campos, SP	\N
96	Ana Clara Ribeiro	anaclara.ribeiro@example.com	$2b$12$...	(11) 93333-0096	333.000.000-96	2	4	2025-09-19 19:28:18.798086-03	\N	Gerente de Afiliados	São José dos Campos, SP	\N
97	Enzo Gabriel Santos	enzogabriel.santos@example.com	$2b$12$...	(11) 93333-0097	333.000.000-97	2	4	2025-09-19 19:28:18.798086-03	\N	Analista de Mídia Social	São José dos Campos, SP	\N
98	Rebeca Cunha	rebeca.cunha@example.com	$2b$12$...	(11) 93333-0098	333.000.000-98	2	5	2025-09-19 19:28:18.798086-03	\N	Analista da Cadeia de Suprimentos	São José dos Campos, SP	\N
99	Leonardo Oliveira	leonardo.oliveira@example.com	$2b$12$...	(11) 93333-0099	333.000.000-99	2	5	2025-09-19 19:28:18.798086-03	\N	Gerente de Compras	São José dos Campos, SP	\N
100	Sarah Sousa	sarah.sousa@example.com	$2b$12$...	(11) 93333-0100	333.000.001-00	2	5	2025-09-19 19:28:18.798086-03	\N	Coordenador de Operações	São José dos Campos, SP	\N
83	Luiz Miguel Pereira	luizmiguel.pereira@example.com	$2b$12$...	(11) 93333-0083	333.000.000-83	2	1	2025-09-19 19:28:18.798086-03	\N	Engenheiro Cloud	São José dos Campos, SP	1
84	Yasmin Lima	yasmin.lima2@example.com	$2b$12$...	(11) 93333-0084	333.000.000-84	2	1	2025-09-19 19:28:18.798086-03	\N	Desenvolvedor Mobile	São José dos Campos, SP	1
85	Henry Carvalho	henry.carvalho@example.com	$2b$12$...	(11) 93333-0085	333.000.000-85	2	1	2025-09-19 19:28:18.798086-03	\N	Administrador de Banco de Dados	São José dos Campos, SP	1
18	Clara Pinto	clara.pinto@example.com	$2b$12$...	(11) 92222-0018	222.000.000-18	2	1	2025-09-19 19:28:18.798086-03	\N	Supervisora de Projetos de P&D	São José dos Campos, SP	1
19	Heitor Correia	heitor.correia@example.com	$2b$12$...	(11) 92222-0019	222.000.000-19	2	1	2025-09-19 19:28:18.798086-03	\N	Supervisor de Qualidade de Software	São José dos Campos, SP	1
23	Bernardo Santos	bernardo.santos@example.com	$2b$12$...	(11) 93333-0023	333.000.000-23	2	1	2025-09-19 19:28:18.798086-03	\N	Engenheiro de Dados Jr	São José dos Campos, SP	1
24	Heloísa Oliveira	heloisa.oliveira@example.com	$2b$12$...	(11) 93333-0024	333.000.000-24	2	1	2025-09-19 19:28:18.798086-03	\N	Analista de QA	São José dos Campos, SP	1
25	Lorenzo Souza	lorenzo.souza@example.com	$2b$12$...	(11) 93333-0025	333.000.000-25	2	1	2025-09-19 19:28:18.798086-03	\N	Desenvolvedor Frontend Sênior	São José dos Campos, SP	1
26	Maria Júlia Silva	mariajulia.silva@example.com	$2b$12$...	(11) 93333-0026	333.000.000-26	2	1	2025-09-19 19:28:18.798086-03	\N	Analista DevOps	São José dos Campos, SP	1
46	Maitê Lima	maite.lima@example.com	$2b$12$...	(11) 93333-0046	333.000.000-46	2	1	2025-09-19 19:28:18.798086-03	\N	Arquiteto de Soluções	São José dos Campos, SP	1
47	Theo Carvalho	theo.carvalho@example.com	$2b$12$...	(11) 93333-0047	333.000.000-47	2	1	2025-09-19 19:28:18.798086-03	\N	Engenheiro de Machine Learning	São José dos Campos, SP	1
48	Aurora Ferreira	aurora.ferreira@example.com	$2b$12$...	(11) 93333-0048	333.000.000-48	2	1	2025-09-19 19:28:18.798086-03	\N	Tester de Software Pleno	São José dos Campos, SP	1
49	Gael Rodrigues	gael.rodrigues@example.com	$2b$12$...	(11) 93333-0049	333.000.000-49	2	1	2025-09-19 19:28:18.798086-03	\N	Analista de Segurança da Informação	São José dos Campos, SP	1
54	Júlia Martins	julia.martins@example.com	$2b$12$...	(11) 93333-0054	333.000.000-54	2	1	2025-09-19 19:28:18.798086-03	\N	Desenvolvedor Jr	São José dos Campos, SP	1
55	Davi Castro	davi.castro2@example.com	$2b$12$...	(11) 93333-0055	333.000.000-55	2	1	2025-09-19 19:28:18.798086-03	\N	Analista de Suporte Técnico	São José dos Campos, SP	1
56	Isabella Dias	isabella.dias@example.com	$2b$12$...	(11) 93333-0056	333.000.000-56	2	1	2025-09-19 19:28:18.798086-03	\N	Desenvolvedor Pleno	São José dos Campos, SP	1
57	Samuel Pires	samuel.pires@example.com	$2b$12$...	(11) 93333-0057	333.000.000-57	2	1	2025-09-19 19:28:18.798086-03	\N	Engenheiro de Software	São José dos Campos, SP	1
74	Maria Clara Castro	mariaclara.castro@example.com	$2b$12$...	(11) 93333-0074	333.000.000-74	2	1	2025-09-19 19:28:18.798086-03	\N	Cientista de Dados	São José dos Campos, SP	1
75	Benício Dias	benicio.dias@example.com	$2b$12$...	(11) 93333-0075	333.000.000-75	2	1	2025-09-19 19:28:18.798086-03	\N	Product Owner	São José dos Campos, SP	1
76	Maria Eduarda Pires	mariaeduarda.pires@example.com	$2b$12$...	(11) 93333-0076	333.000.000-76	2	1	2025-09-19 19:28:18.798086-03	\N	Scrum Master	São José dos Campos, SP	1
77	Vitor Hugo Ribeiro	vitorhugo.ribeiro@example.com	$2b$12$...	(11) 93333-0077	333.000.000-77	2	1	2025-09-19 19:28:18.798086-03	\N	Engenheiro de QA	São José dos Campos, SP	1
82	Ana Liz Silva	analiz.silva@example.com	$2b$12$...	(11) 93333-0082	333.000.000-82	2	1	2025-09-19 19:28:18.798086-03	\N	Desenvolvedor de Software	São José dos Campos, SP	1
22	Alice Fernandes	alice.fernandes@example.com	$2b$12$...	(11) 93333-0022	333.000.000-22	2	1	2025-09-19 19:28:18.798086-03	\N	Desenvolvedora Backend Pleno	São José dos Campos, SP	1
27	Nicolas Pereira	nicolas.pereira@example.com	$2b$12$...	(11) 93333-0027	333.000.000-27	2	1	2025-09-19 19:28:18.798086-03	\N	Desenvolvedor Fullstack Jr	São José dos Campos, SP	1
101	Usuario Teste Admin	admin@teste.com	$2a$10$UIIbDa5il/hL3SruzsGeq.wUNsyHnGaAaN84OA9kCsT/rD2t2UPKq	12999999999	\N	1	1	\N	Usuário para testes	Admin de Teste	Sistema	\N
102	Usuario Teste Gestor	gestor@teste.com	$2a$10$N2f8SznY5jeKy4Sbeif40e6SHMkSatGyxvXUsIj19N4VHVfVHEeou	12999999999	\N	3	1	\N	Usuário para testes de GESTOR	Gestor de Teste	Sistema	\N
103	Usuario Teste Padrao	user@teste.com	$2a$10$/.TKR/GPgxiqqJO7giMrg.IjQ8baCKdFRpuqnmw2zBGyNk4.uKHI.	12999999999	\N	2	1	\N	Usuário para testes de USER	Padrão de Teste	Sistema	\N
104	Supervisor TI	supervisor-ti@teste.com	$2a$10$IVNzlHwciXmF2VjG1emeYeSe/DA4XzJQhPzOASfkWzCCj7V.I4QX6	\N	\N	2	1	\N	\N	\N	\N	\N
105	Diretor TI	diretor-ti@teste.com	$2a$10$pMcYk2eU6jU0IDvi00OoLeqMOn/UlGrFf9frM0cYL7lOJiTo0bD2G	\N	\N	1	1	\N	\N	\N	\N	\N
106	Colaborador TI	dev-ti@teste.com	$2a$10$6elTzP80NtDV5yd.rLgZYu.OJfz2y2OliYBpxYm9RIjfRFC0JgxM6	\N	\N	3	1	\N	Meu perfil foi atualizado por mim mesmo.	\N	\N	\N
\.


--
-- TOC entry 4985 (class 0 OID 18716)
-- Dependencies: 225
-- Data for Name: tb_cad_funcionario_avaliacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_funcionario_avaliacao (codigo, codigo_funcionario_avalidado, codigo_avaliacao, comentario_colaborador, comentario_supervisao, resultado_status, nota) FROM stdin;
\.


--
-- TOC entry 5000 (class 0 OID 18900)
-- Dependencies: 240
-- Data for Name: tb_cad_funcionario_avalicacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_funcionario_avalicacao (codigo, comentario_colaborador, comentario_supervisao, nota, resultado_status, codigo_avalicacao, codigo_funcionario_avalidado) FROM stdin;
25	\N	\N	\N	PENDENTE	20	8
26	Seu desempenho técnico está ótimo. Continue assim.	Bom progresso em Java, mas pode melhorar a colaboração em reuniões de equipe.	3	APROVADO	21	104
\.


--
-- TOC entry 4987 (class 0 OID 18723)
-- Dependencies: 227
-- Data for Name: tb_cad_funcionario_certificado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_funcionario_certificado (codigo, codigo_funcionario, certificado) FROM stdin;
1	106	Certificação de Teste Pessoal
\.


--
-- TOC entry 4989 (class 0 OID 18727)
-- Dependencies: 229
-- Data for Name: tb_cad_funcionario_competencia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_funcionario_competencia (codigo_funcionario, codigo_competencia, nota, inserido_por) FROM stdin;
2	10	\N	\N
3	5	\N	\N
4	1	\N	\N
5	10	\N	\N
6	10	\N	\N
7	6	\N	\N
9	1	\N	\N
10	10	\N	\N
11	5	\N	\N
12	5	\N	\N
13	3	\N	\N
14	2	\N	\N
15	7	\N	\N
16	9	\N	\N
17	10	\N	\N
19	5	\N	\N
20	4	\N	\N
21	1	\N	\N
22	5	\N	\N
26	4	\N	\N
27	2	\N	\N
28	7	\N	\N
29	8	\N	\N
30	8	\N	\N
31	8	\N	\N
32	8	\N	\N
33	9	\N	\N
34	5	\N	\N
35	10	\N	\N
36	3	\N	\N
37	8	\N	\N
38	2	\N	\N
39	2	\N	\N
40	3	\N	\N
41	6	\N	\N
42	10	\N	\N
43	8	\N	\N
44	6	\N	\N
45	6	\N	\N
46	3	\N	\N
47	1	\N	\N
48	1	\N	\N
49	3	\N	\N
50	6	\N	\N
51	1	\N	\N
52	9	\N	\N
53	10	\N	\N
54	6	\N	\N
55	2	\N	\N
56	8	\N	\N
57	2	\N	\N
58	8	\N	\N
59	9	\N	\N
60	4	\N	\N
61	6	\N	\N
62	7	\N	\N
63	3	\N	\N
64	9	\N	\N
65	9	\N	\N
66	2	\N	\N
67	3	\N	\N
68	7	\N	\N
69	3	\N	\N
70	3	\N	\N
71	8	\N	\N
72	8	\N	\N
73	8	\N	\N
74	8	\N	\N
75	2	\N	\N
76	9	\N	\N
77	1	\N	\N
78	1	\N	\N
79	3	\N	\N
80	6	\N	\N
81	10	\N	\N
82	2	\N	\N
83	2	\N	\N
84	9	\N	\N
85	10	\N	\N
86	10	\N	\N
87	3	\N	\N
88	3	\N	\N
89	1	\N	\N
90	7	\N	\N
91	1	\N	\N
92	4	\N	\N
93	7	\N	\N
94	10	\N	\N
95	6	\N	\N
96	8	\N	\N
97	6	\N	\N
98	4	\N	\N
99	10	\N	\N
100	1	\N	\N
2	6	\N	\N
3	10	\N	\N
4	8	\N	\N
5	6	\N	\N
6	8	\N	\N
9	9	\N	\N
10	1	\N	\N
11	6	\N	\N
12	4	\N	\N
13	9	\N	\N
14	10	\N	\N
15	9	\N	\N
16	3	\N	\N
17	4	\N	\N
20	9	\N	\N
21	4	\N	\N
22	10	\N	\N
26	10	\N	\N
27	9	\N	\N
28	10	\N	\N
29	5	\N	\N
30	10	\N	\N
31	10	\N	\N
32	7	\N	\N
34	4	\N	\N
35	2	\N	\N
36	4	\N	\N
37	7	\N	\N
38	1	\N	\N
39	3	\N	\N
40	6	\N	\N
41	4	\N	\N
42	7	\N	\N
44	9	\N	\N
45	5	\N	\N
48	2	\N	\N
49	10	\N	\N
50	7	\N	\N
51	3	\N	\N
52	3	\N	\N
53	5	\N	\N
54	7	\N	\N
55	3	\N	\N
56	3	\N	\N
57	9	\N	\N
58	3	\N	\N
60	7	\N	\N
61	1	\N	\N
62	8	\N	\N
63	4	\N	\N
65	8	\N	\N
66	7	\N	\N
67	2	\N	\N
68	5	\N	\N
69	4	\N	\N
70	2	\N	\N
71	3	\N	\N
72	7	\N	\N
73	5	\N	\N
74	6	\N	\N
75	7	\N	\N
76	6	\N	\N
77	6	\N	\N
78	4	\N	\N
79	5	\N	\N
80	10	\N	\N
82	6	\N	\N
83	4	\N	\N
84	3	\N	\N
85	9	\N	\N
86	8	\N	\N
87	5	\N	\N
88	4	\N	\N
89	8	\N	\N
90	9	\N	\N
91	2	\N	\N
93	8	\N	\N
94	4	\N	\N
95	8	\N	\N
96	2	\N	\N
97	9	\N	\N
98	3	\N	\N
99	3	\N	\N
100	10	\N	\N
1	5	\N	\N
1	7	\N	\N
1	8	\N	\N
1	1	\N	\N
1	2	\N	\N
1	4	\N	\N
18	5	\N	\N
18	1	\N	\N
18	4	\N	\N
104	5	\N	\N
104	6	\N	\N
104	7	\N	\N
104	1	\N	\N
106	5	\N	\N
106	6	\N	\N
106	7	\N	\N
106	8	\N	\N
106	1	\N	\N
8	5	\N	\N
8	6	\N	\N
8	7	\N	\N
8	8	\N	\N
8	1	\N	\N
23	5	\N	\N
23	6	\N	\N
23	7	\N	\N
23	8	\N	\N
23	1	\N	\N
24	5	\N	\N
24	6	\N	\N
24	7	\N	\N
24	8	\N	\N
24	1	\N	\N
25	5	\N	\N
25	6	\N	\N
25	7	\N	\N
25	8	\N	\N
25	1	\N	\N
\.


--
-- TOC entry 4990 (class 0 OID 18731)
-- Dependencies: 230
-- Data for Name: tb_cad_funcionario_historico_experiencia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_funcionario_historico_experiencia (codigo, cargo, empresa, data_inicio, data_fim, descricao, codigo_funcionario) FROM stdin;
10	Analista de Dados	DataCorp Analytics	2020-01-15	2022-05-30	Criação de dashboards em Power BI e relatórios gerenciais.	15
11	Cientista de Dados	Intellidata	2022-06-01	\N	Desenvolvimento de modelos de machine learning para previsão de vendas.	15
12	Desenvolvedor Front-end	WebPixel Design	2021-02-10	\N	Desenvolvimento de interfaces com React e TypeScript.	22
13	Analista de RH	Conecta RH	2018-05-20	2021-02-10	Responsável por recrutamento e seleção de novos talentos.	1
14	Coordenador de RH	Innovate Corp	2021-03-01	\N	Coordenação da equipe de RH e desenvolvimento de políticas internas.	1
15	Estagiário de Marketing	Visão Digital	2022-01-10	2023-01-09	Apoio na criação de conteúdo para redes sociais e e-mail marketing.	2
16	Analista de Marketing Jr	Visão Digital	2023-01-10	\N	Gerenciamento de campanhas de mídia paga e análise de métricas.	2
17	Desenvolvedor Back-End Pleno	Future Systems	2021-11-15	\N	Manutenção e desenvolvimento de novas features para a API principal.	3
18	Analista Financeiro Jr	Finance Corp	2019-10-01	2022-08-30	Responsável pelo controle de contas a pagar e a receber.	4
19	Analista Financeiro Pleno	Finance Corp	2022-09-01	\N	Análise de fluxo de caixa e elaboração de relatórios gerenciais.	4
20	Designer Gráfico	Pixel Criativo	2020-06-01	2023-03-15	Criação de materiais gráficos para campanhas online e offline.	5
21	Analista de Suporte Técnico	HelpDesk Solutions	2022-04-12	\N	Suporte técnico nível 1 e 2 para clientes de software.	6
22	Engenheiro de DevOps Jr	Cloud Native Inc	2021-08-20	2023-07-30	Automação de pipelines de CI/CD e monitoramento de infraestrutura.	7
23	Engenheiro de DevOps Pleno	Cloud Native Inc	2023-08-01	\N	Gerenciamento de clusters Kubernetes e otimização de custos em nuvem AWS.	7
24	Scrum Master	Agile Way	2022-09-01	\N	Facilitação de cerimônias Scrum e remoção de impedimentos para a equipe.	8
25	Analista de QA (Qualidade)	TestRight	2020-02-18	2023-01-20	Criação e execução de casos de teste manuais e automatizados.	9
26	Especialista em QA	TestRight	2023-01-21	\N	Liderança técnica da equipe de QA e definição de estratégias de teste.	9
27	Product Owner	Product First	2021-05-15	\N	Gerenciamento do backlog do produto e priorização de features.	10
28	Desenvolvedor Front-End Sênior	WebPixel Design	2019-03-01	\N	Liderança técnica no desenvolvimento da interface do principal produto da empresa.	11
29	Analista de Business Intelligence	DataPrime Analytics	2022-11-10	\N	Desenvolvimento de dashboards em Power BI para a área comercial.	12
30	Desenvolvedor Mobile (Android)	AppMakers	2020-07-07	2024-01-20	Desenvolvimento do aplicativo de e-commerce da empresa.	13
31	Head de Vendas	SalesForce	2018-01-10	\N	Liderança da equipe de vendas nacional.	14
32	Assistente Administrativo	Office Pro	2023-02-20	\N	Apoio nas rotinas administrativas e financeiras.	15
33	Desenvolvedor Python Pleno	PySystems	2021-06-14	\N	Desenvolvimento de microsserviços e automações em Python.	16
34	Tech Lead	PySystems	2024-01-01	\N	Liderança técnica do time de back-end.	16
35	UX/UI Designer	Creative Minds	2022-03-01	\N	Criação de protótipos e interfaces de alta fidelidade para aplicativos web.	17
36	DBA (Administrador de Banco de Dados)	DataGuard	2017-09-25	\N	Manutenção e otimização de bancos de dados PostgreSQL e SQL Server.	18
37	Analista de Segurança da Informação	SecureNet	2021-10-10	\N	Monitoramento de ameaças e implementação de políticas de segurança.	19
38	Desenvolvedor C#/.NET Sênior	DotNet Experts	2020-01-30	\N	Desenvolvimento de sistemas para o setor bancário com a plataforma .NET.	20
39	Gerente de Marketing	Visão Digital	2024-02-01	\N	Liderança da equipe de marketing e definição de estratégias.	2
40	Analista de Sistemas	Future Systems	2020-05-12	2021-11-14	Levantamento de requisitos e documentação de sistemas.	3
41	Gerente Financeiro	Finance Corp	2024-01-10	\N	Liderança do departamento financeiro.	4
42	Arquiteto de Soluções	Cloud Native Inc	2024-03-01	\N	Desenho de arquiteturas de software escaláveis em nuvem.	7
43	PO (Product Owner) Junior	Product First	2019-11-01	2021-05-14	Apoio na gestão do backlog e escrita de estórias de usuário.	10
44	Analista de BI Pleno	DataPrime Analytics	2024-01-15	\N	Criação de modelos de dados e dashboards complexos.	12
45	DBA Júnior	DataGuard	2015-02-11	2017-09-24	Monitoramento e rotinas de backup de bancos de dados.	18
46	Coordenador de Vendas	SalesForce	2016-03-15	2017-12-20	Gestão de uma equipe regional de vendedores.	14
47	Desenvolvedor Java Pleno	Inova Corp	2020-08-01	\N	Desenvolvimento de sistemas para o setor de seguros.	20
48	Analista de Recrutamento	Conecta RH	2022-01-10	\N	Foco em recrutamento de profissionais de tecnologia.	1
49	Desenvolvedor de Testes Automatizados	TestRight	2024-02-01	\N	Criação de scripts de automação de testes com Selenium e Cypress.	9
50	Gerente de Contas	Visão Digital	2021-03-15	2022-12-20	Relacionamento e gestão de contas de grandes clientes.	2
51	Arquiteto de Dados	DataPrime Analytics	2023-01-10	\N	Modelagem de dados e estruturação de data warehouses.	12
52	Desenvolvedor Full-Stack Pleno	Agile Way	2020-10-01	2022-08-30	Atuação tanto no front-end (Angular) quanto no back-end (Node.js).	8
53	Líder de Suporte Técnico	HelpDesk Solutions	2024-03-01	\N	Gestão da equipe de suporte e de indicadores de atendimento (SLAs).	6
54	Especialista em Marketing de Conteúdo	Visão Digital	2023-02-01	\N	Criação de blog posts, e-books e webinars.	2
55	Desenvolvedor iOS	AppMakers	2022-05-20	\N	Desenvolvimento de aplicativos para a plataforma iOS com Swift.	13
56	Analista de Infraestrutura	Cloud Native Inc	2019-01-15	2021-08-19	Gerenciamento de servidores e redes.	7
57	Coordenador de Design	Creative Minds	2024-04-01	\N	Liderança da equipe de UX/UI Designers.	17
58	Gerente de Produto Sênior	Product First	2023-06-01	\N	Definição da visão estratégica e roadmap do produto.	10
59	Engenheiro de Machine Learning	Intellidata	2023-09-10	\N	Implementação de algoritmos de IA para personalização de serviços.	15
60	Analista de Marketing Pleno	Visão Digital	2024-01-10	2024-01-09	Gerenciamento de campanhas de mídia paga e análise de métricas.	2
61	Engenheiro de Software	Google	2023-01-10	\N	Trabalho em projetos de larga escala.	21
62	Cientista de Dados Sênior	Facebook	2022-01-10	\N	Análise de dados para tomada de decisões estratégicas.	22
63	Engenheiro de Machine Learning	Netflix	2021-01-10	\N	Desenvolvimento de sistemas de recomendação.	23
64	Gerente de Produto	Amazon	2020-01-10	\N	Liderança de equipes de desenvolvimento de produtos.	24
65	Desenvolvedor Front-End	Microsoft	2019-01-10	\N	Desenvolvimento de interfaces de usuário para produtos da Microsoft.	25
66	Desenvolvedor Back-End	Apple	2018-01-10	\N	Desenvolvimento de sistemas para a Apple.	26
67	Engenheiro de DevOps	Oracle	2017-01-10	\N	Automação de processos de desenvolvimento e operações.	27
68	Analista de Segurança da Informação	IBM	2016-01-10	\N	Proteção de sistemas contra ameaças cibernéticas.	28
69	Arquiteto de Soluções	Salesforce	2015-01-10	\N	Desenho de soluções para clientes da Salesforce.	29
70	Gerente de Projetos	SAP	2014-01-10	\N	Liderança de projetos de implementação de sistemas SAP.	30
1	Dev de Teste	Empresa Teste SA	2024-01-01	\N	Minha própria experiência	106
2	Dev de Teste	Empresa Teste SA	2024-01-01	\N	Minha própria experiência	106
3	Dev de Teste	Empresa Teste SA	2024-01-01	\N	Minha própria experiência	106
\.


--
-- TOC entry 4992 (class 0 OID 18737)
-- Dependencies: 232
-- Data for Name: tb_cad_perfil; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_perfil (codigo, nome, descricao) FROM stdin;
1	Diretoria	Acesso total ao sistema.
2	Supervisão	Acesso para edição do próprio perfil.
3	Colaborador	Acesso para edição do perfil Padrão
\.


--
-- TOC entry 4994 (class 0 OID 18743)
-- Dependencies: 234
-- Data for Name: tb_cad_pergunta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_pergunta (codigo, pergunta, codigo_competencia, tipo_pergunta) FROM stdin;
47	a	1	texto
48	Qual sua experiência com Java?	1	texto
\.


--
-- TOC entry 4996 (class 0 OID 18747)
-- Dependencies: 236
-- Data for Name: tb_cad_pergunta_opcao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_pergunta_opcao (codigo, codigo_pergunta, descricao_opcao, is_correta) FROM stdin;
\.


--
-- TOC entry 4998 (class 0 OID 18754)
-- Dependencies: 238
-- Data for Name: tb_cad_resposta_colaborador; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cad_resposta_colaborador (codigo, codigo_funcionario_avaliacao, codigo_pergunta, resposta_texto, codigo_pergunta_opcao_selecionada) FROM stdin;
26	26	48	Tenho 2 anos de experiência com Java 11 e Spring Boot.	\N
\.


--
-- TOC entry 5018 (class 0 OID 0)
-- Dependencies: 218
-- Name: tb_cad_area_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_area_codigo_seq', 5, true);


--
-- TOC entry 5019 (class 0 OID 0)
-- Dependencies: 220
-- Name: tb_cad_avaliacao_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_avaliacao_codigo_seq', 21, true);


--
-- TOC entry 5020 (class 0 OID 0)
-- Dependencies: 241
-- Name: tb_cad_avaliacao_pergunta_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_avaliacao_pergunta_codigo_seq', 68, true);


--
-- TOC entry 5021 (class 0 OID 0)
-- Dependencies: 223
-- Name: tb_cad_competencia_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_competencia_codigo_seq', 10, true);


--
-- TOC entry 5022 (class 0 OID 0)
-- Dependencies: 226
-- Name: tb_cad_funcionario_avalicacao_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_funcionario_avalicacao_codigo_seq', 26, true);


--
-- TOC entry 5023 (class 0 OID 0)
-- Dependencies: 242
-- Name: tb_cad_funcionario_certificado_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_funcionario_certificado_codigo_seq', 1, true);


--
-- TOC entry 5024 (class 0 OID 0)
-- Dependencies: 228
-- Name: tb_cad_funcionario_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_funcionario_codigo_seq', 106, true);


--
-- TOC entry 5025 (class 0 OID 0)
-- Dependencies: 231
-- Name: tb_cad_funcionario_perfil_experiencia_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_funcionario_perfil_experiencia_codigo_seq', 3, true);


--
-- TOC entry 5026 (class 0 OID 0)
-- Dependencies: 233
-- Name: tb_cad_perfil_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_perfil_codigo_seq', 2, true);


--
-- TOC entry 5027 (class 0 OID 0)
-- Dependencies: 235
-- Name: tb_cad_pergunta_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_pergunta_codigo_seq', 48, true);


--
-- TOC entry 5028 (class 0 OID 0)
-- Dependencies: 237
-- Name: tb_cad_pergunta_opcao_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_pergunta_opcao_codigo_seq', 12, true);


--
-- TOC entry 5029 (class 0 OID 0)
-- Dependencies: 239
-- Name: tb_cad_resposta_colaborador_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cad_resposta_colaborador_codigo_seq', 26, true);


-- Completed on 2025-11-11 16:42:24

--
-- PostgreSQL database dump complete
--

\unrestrict DC6R4r7mdQ3dV7mR8wfg2XHHqN4i6ErXctmGVT4G9XpiTlxTTOVtAFV0DRQASKN

